server {
                server_name auth.karavanglobal.space;
    		client_max_body_size 3M;
    		location / {
                        proxy_pass http://localhost:6049;
                        }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/auth.karavanglobal.space/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/auth.karavanglobal.space/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {

                listen 80;
                server_name auth.karavanglobal.space;
}


server {
    if ($host = auth.karavanglobal.space) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


                server_name auth.karavanglobal.space;
    listen 80;
    return 404; # managed by Certbot


}